msg = ["ale urocze",
    "a nie jednak nie",
    "Spierdalaj",
    "Hiv też istiniej od 100 lat a sie nie uodporniliśmy jakoś",
    "socjalizm jedynym sposobem na dobry świat",
    "dawaj daba",
    "No i to jest człek czynu",
    "Drugi raz nie przejdzie",
    "położy się człowiek na glebe i będzie git",
    "błagam kończ waśćwstydu oszczędź",
    "Oof",
    "to trzeba dla potomnych uwiecznić",
    "Szotuj ktoś",
    "Kurrrrwa",
    "Nagrywaj",
    "Zupełnie jak za czasów francuskich",
    "To ona teraz wybiera nad kim się znęca",
    "Alee czerowono",
    "Umrzyj",
    "Spierdalaj",
    "was",
    "chciałem powiedzieć niskie podatki no ale...",
    "Wiesz jak sie nazywa coś co powinno być  a nie ma?",
    "ustawić se coś uroczego",
    "heheh",
    "umrzemy",
    "prawie",
    "to co to za wypłosz",
    "a na trufle nie bierze sie świń?",
    "fu",
    "szczerze mówiąc idk",
    "tzn no nikt ci nie każe siedzieć na lekcji",
    "czy tylko ja tu widze gębę",
    "no",
    "zależy jak otym myśleć",
    "O kij tu chodzi",
    "no tera to mi nie wmówisz ze go slyszysz",
    "TO ZNACZY PALIĆ",
    "co",
    "masz cos ze lbem",
    "I wtedy na apka na japka to by była jappka",
    "kaputt",
    "czy wieżchołek musi koniecznie być w zagrodzie czy może być tylko jej narożnikiem",
    "nie do końca",
    "h̶̭̅ă̴͂ć̶͘ḳ̸̆ẻ̴̒r̶̛̕m̷̛̏â̶̚n̴̔͠",
    "sorry wojtyek musze to sprwdzić",
    "to miało być do nauki własnej",
    "piekne",
    "jakiś bloat tfu",
    "a przede wszystkim to",
    "rzyć mi sie nie chce",
    "ich will sterben",
    "e no ja przeczytałem"
    "das Leben ruinieren",
    "erkenne",
    "verschiedene",
    "mp cppr anthem",
    "jebnij nikotinsucht",
    "i internet sucht",
    "wiecej lasek pali czy faców",
    "terapie machen",
    "Ustaw se ktoś to na tło https://media.discordapp.net/attachments/774178902901522453/779461960915746846/ar.jpg",
    "tf",
    "tf",
    "neat",
    "tf",
"f u",
"f u",
"ona pyta tych co mają mało ocen",
"znamy algorytm",
"kaputt",
"wyebalo mnie na chwile xdd",
"fu",
"i nierówności",
"i z tymi przypadkami",
"ale to pewnie rozwiązywanie równań",
"szczerze mówiąc idk",
"ona nieironiczne korzysta z edge",
"to co to za wypłosz",
"a na trufle nie bierze sie świń?",
"🎲",
"no lae chyba ta opcja że musi być jest logiczniejsza",
"czy wieżchołek musi koniecznie być w zagrodzie czy może być tylko jej narożnikiem",
"zależy jak otym myśleć",
"nie do końca",
"chociaż niby",
"powinien",
"taaa",
"czyli (0; 7,5)",
"ale to 15 -2x nie liczy sie obwód",
"i musi być ten narożnik",
"bo jeszcze biore pod uwage że narożnik musi być w zagrodzie",
"a nie (0,15>?",
"tzn no nikt ci nie każe siedzieć na lekcji",
"czy tylko ja tu widze gębę",
"tak była umowa",
"i tak sama przedłuża o 10",
"niezle trio",
"zaprosiłem cie xdd",
"ja ci coś zara zrobie za ten cynizm",
"alik kurłą",
"no",
"ask him for consent",
"gimp życiem",
"kij ci w oko walić photoshopa",
"In arch we go full in",
"może jesteś virgin ubuntu user",
"wasze tak nasze nie xdd",
"bo sam nie umie go włączyć i każdy kto go używa musi być magiem lvl 100",
"taki typowy boomer, widzi darkmode i magia super hacker",
"lubi darkmode",
"no tera to mi nie wmówisz ze go slyszysz",
"tyko u mn go tak tnie?",
"lol akiko wiedziałes o WIN + Shift + S",
"ja nawe t połowe 6 widze",
"taaa",
"i czy zglosimy",
"czy patrzymy",
"moze ona nas sprawdza",
"you ain't fucken with me right",
"bo to tylko u mn widac tyko edytor?",
"moze se poszla?",
"dziwne że sie jeszcze nie przyczepiła że slajdy sie nie zmieniaja",
"tak to sie konczy jak udostępniasz okno edytora",
"kurła te układy piękne",
"do you want to lose your breathing privilages?",
"you've lost your right to breathe",
"die",
"teskni za nami",
"tylko pepsi wild cherry flavour",
"niiiiiiiic",
"ale kto przejmuje majatek jak umra?",
"nie trzba nikogo wtedy zmuszac",
"500 plus tym co sie poddadza sami",
"masz cos ze lbem",
"osiagniecniem",
"jeast",
"co",
"ja nic nie piłem",
"https://medium.com/@Peter_UXer/small-sized-and-beautiful-gifs-with-ffmpeg-25c5082ed733",
"wróc sie na chwile na metme",
"to za dużo powiedziane",
"a tam od razu nic",
"ciekewe co dzisiej bedzie na infie",
"jak  świerzaki",
"la courbure de la terre est étonnant",
"taczek",
"a kto robi roomtour",
"kids these days",
"f u",
"manometer",
"V = S * h",
"a V = V2",
"S = V / h",
"die zeit ist knapp",
"git",
"luknij na mojego stream czy jest audio",
"na streamie",
"słychać dźwięk?",
"no dodajeło jakiś znaczek a potem zabrało",
"nic nie robi xdd",
"a jak wszyscy nazwali to czytanie.pdf....",
"bo wiecie jak jest ta sam nazwa dokumentu to może zamienić xdd",
"auf wiederhoren",
"hujooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo",
"jooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo",
"hujoooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo",
"nie no geralnie na nast stronie po tescie sa idpowiedzi do wszystkich testó",
"na nast stronie sa odpowiedzi...",
"L",
"5",
"wait co wy dostaliscie",
"miłęgo weekendu xdd",
"https://qutebrowser.com",
"ty tam jestes?",
"streamuj",
"f",
"rip",
"zawo jak najebany w sufit sie gapi",
"Routen",
"Tour",
"Trasse",
"lol ja tak niemiętnie to zoo robiłem że aż bunio limity zmienił xdd",
"zrób chociaż jedno zeby 6 dostac",
"warum?",
"ty robiles oi?",
"nie wiem",
"ja spr z fizy pisałem cymbale",
"no joke",
"80%",
"a wilogoć to akurat jest",
"no taka piwnica na czwartym pietrze",
"wiesz no nawet w piwnicy są okna",
"no i wykrakał",
"weź nie kracz",
"nie bo wy",
"tzn oni wsm też mają swoje getto",
"fu",
"tf....",
"tf",
"vc",
"tf",
"To wina microshafta",
"Bo znowu ją wywali xdd",
"U was też sie totalnie zarżnęło?",
"No nie do konca bo oprócz 2 sa jeszcze inne liczby pierwsze",
"bo ciagle 'i' na 2 ustawiasz",
"L",
"weź daj range L",
"L",
"L",
"L",
"L",
"L",
"L",
"L",
"LLLLL",
"L",
"L",
"L",
"L",
"L",
"L",
"L",
"L",
"L",
"L",
"L",
"Najpierw obrażają a potem jeszcze nękają",
"O kij wam znowu chodzi",
"on  sie pyta o zadanie z ilocampa ez a ty z tego masz 100%",
"no własne",
"kurwa",
"Gościu",
"muzgu sprawdz na ilocamp ez ze masz xdd",
"no masz to",
"jak masz",
"a czemu ty nie masz?",
"kto mu powie ze nie ma udostepnionego ekranu...",
"ale on bylo ez",
"mi też sie nie chce",
"no jakoś mam złe doświadczenia z dp",
"eeee",
"właśnie mówi ze nie wszystko sprawdzi",
"wrzuć na luz",
"jak porzadny produkt microsofta",
"tym razem nie ja",
"kto na ochotnika",
"im not",
"Y tho",
"Y",
"die zeit ist knapp!",
"die zeit ist knapp",
"sprowadzilem piglina",
"umawailismy sie ostatio",
"nie ma nas",
"ale z liczbami pierwszymi to chyba w tych zadaniach starczy dzielic i patrzec czy sie nie dzieli",
"mozesz wymyslic jak napisac",
"a no to robisz i wstawiasz",
"w arkuszach maturalnych'",
"no jest tresc",
"tyko dostajesz dane w pliku i twoj program ma pracowac na plikach",
"normalnie jak inne zadania",
"no cos tam chyba trzea bylo wypisac liczby pierwsze i cos z nimi robic",
"no trzea te ktore da sie wstawic zrobic do 11.11",
"Istotne jest to że te = są na koncu",
"i jak ci idzie?",
"to dawaj co to za filmik: GRTCANDDEA3TAIBWGUQDKOBAGM2CANJSEA2TEIBWMYQDGMRAGM4CA===",
"wiesz no pajęcze zmysły",
"tzn ja domyślam sie ze to rick roll ale nie moge wpaść od czego zaczać",
"ﮡ",
"w końcu zainstalowałem se aplikacje do wyświetlania powiadomień systemowych i działa",
"działa!",
"yo",
"beka jest jak w ogole nie usatwisz hasla nie mozesz sie zalogowac xdd",
"wirus is very dangerous for your computer mam'",
"root : toor",
"pog",
"password1",
"teeth",
"her",
"sachsen",
"sachsen",
"sachsen",
"sachsen",
"sachsen",
"hamburg",
"shulkery...",
"coś zostawiles przy farmie golda...",
"mikrofon działa mi tak że nie działa",
"nie oczekuje tego",
"heh wyjebało mi mikrofon",
"die",
"wypisze te same cyferki tylko w innej kolejnosci",
"was",
"czyli delta e",
"bo to zmiana energii",
"jeszcze wiececj wodolaniska",
"zabawa",
"i git",
"u wa też teamsy wyjebalo?",
"was...",
"znowu xdd",
"https://www.desmos.com/calculator",
"https://www.desmos.com",
"┬─┬ ノ( ゜-゜ノ)",
"__",
"┬─┬ ノ( ゜-゜ノ)",
"(╯°□°）╯︵ ┻━┻",
"🌈 🌈 🌈 🌈 🌈 🌈 🌈 🌈 🌈 🌈 🌈 🌈 🌈 🌈 🌈 🌈 🌈 🌈 🌈 🌈 🌈 🌈 🌈 🌈 🌈 🌈 🌈 🌈 🌈 🌈 🌈 🌈 🌈 🌈 🌈",
"🚅 🚅 🚅 🚅 🚅 🚅 🚅 🚅 🚅 🚅 🚅 🚅 🚅 🚅 🚅 🚅 🚅 🚅 🚅 🚅 🚅 🚅 🚅 🚅 🚅 🚅 🚅 🚅 🚅 🚅 🚅 🚅 🚅",
"🍺🐻‍❄️ 🍺 🐝🍺🐻‍❄️ 🍺 🐝🍺🐻‍❄️ 🍺 🐝🍺🐻‍❄️ 🍺 🐝",
"🍺🐻‍❄️ 🍺 🐝🍺🐻‍❄️ 🍺 🐝🍺🐻‍❄️ 🍺 🐝🍺🐻‍❄️ 🍺 🐝🍺🐻‍❄️ 🍺 🐝🍺🐻‍❄️ 🍺 🐝🍺🐻‍❄️ 🍺 🐝🍺🐻‍❄️ 🍺 🐝🍺🐻‍❄️ 🍺 🐝🍺🐻‍❄️ 🍺 🐝🍺🐻‍❄️ 🍺 🐝",
"Kij ci w oko",
"sm *= (pow(i,cdiv+1)-1)/(i-1);",
"oni sie na tym znają",
"wszystko wrócilo",
"<@!432552397550780446> wbijaj",
"no",
"ale to ip jest takie samo jak poprzedni",
"przypadkiem cn xddd",
"pog",
"a                                                                                                                                                                                   a",
"a",
"pog",
"na na na na",
"🏳️‍🌈",
"dawaj ktoś robienie deep dabów",
"sprytne bo do końca nic nie musze robić xdd",
"pog",
"bo nie każe sie pokazywać i wyginać",
"tutaj bardziej",
"oooo",
"na wf dawajcie",
"na wf",
"ale jak to zadziała to pog",
"hisu nie ma",
"To kto go ma xddd",
"wbijaj moze dam ci nawet jakies surowce",
"mozesz wbijac",
"k",
"chyba serwer leży",
"Tylko ma",
"Wpływa bo nie mogą wtedy podnosić żarcia",
"włącz mob griefing żeby sie villagery mogły mnożyć",
"Ale kurła oprócz tego z anime to w miare sensowne",
"to impostor",
"może sama posiedzi se",
"A nie jednak nie",
"Możecie ją wywalić xdd",
"który to xdd",
"No ale koniec faktycznie powinien być",
"Ale urocze",
"ale urocze",
"jest git",
"a jak z tym owt",
"W sumie sensowny wynik",
"Ale serio jak masz 17 lat i urodziny jakoś pół roku temu to tyle wychodzi",
"day 6394 without sex",
"W sumie sensowny wynik",
"Ale to łatwo sie da policzyć",
"Giiit",
"Hiv też istiniej od 100 lat a sie nie uodporniliśmy jakoś",
"czy usprawiedliwi",
"Albo z owt",
"żeś wykrakała",
"socjalizm jedynym sposobem na dobry świat",
"tylko miedzy klatkami przy 10 fps wpadł",
"był",
"dab",
"dab",
"dab",
"dab",
"dawaj daba",
"No i to jest człek czynu",
"Drugi raz nie przejdzie",
"położy sie człowiek na glebe i bedzie git",
"Dobrze że mam wysoko kamerke xdd",
"błagam kończ waśćwstydu oszczędź",
"ufff",
"Big oooof",
"Oof",
"to trzeba dla potomnych uwiecznić",
"Nagrywaj",
"Szotuj ktoś",
"Mów do słupa a słup d...",
"Zupełnie jak za czasów francuskich",
"Pokazowa",
"To ona teraz wybiera nad kim sie znęca",
"Alee czerwono",
"kij ja wie",
"Spierdalaj",
"Umrzyj",
"while true; do echo s; done;",
"chciałem powiedzieć niskie podatki no ale...",
"Wiesz jak sie nazywa coś co powinno być  a nie ma?",
"was",
"@everyone ustawcie też przez apke mobilną tam chyba szybciej aktualizują",
"@everyone",
"Dawać",
"https://duckduckgo.com/?q=david+zinn&iax=images&ia=images",
"Nooo",
"ustawić se coś uroczego na profilowe",
"Eee tam chyba dzierga mocno pilnować nie bedzie",
"ej no nie jest aż tak źłe",
"przynajmniej innych nie pyta",
"oj tam lanie wody",
"a ja powiedziałem ze wojtek mówił",
"Bo woytek ma paweł na drugie cn xddd",
"heheh",
"ona faktycznie jest waszą ciocią?",
"prawie",
"e no ja przeczytałem",
"to ta od niderlandzkiego",
"umrzemy",
"ich will sterben",
"rzyć mi sie nie chce",
"aaa",
"was?",
"jakiś bloat tfu",
"ale lepsze to niż  one note",
"piekne",
"to miało być do nauki własnej",
"no",
"a czemu",
"sorry wojtyek musze to sprwdzić",
"można wyciszać i wywalać",
"Znowu nie zabrała kontroli",
"h̶̭̅ă̴͂ć̶͘ḳ̸̆ẻ̴̒r̶̛̕m̷̛̏â̶̚n̴̔͠",
"wysłałem",
"a walić to microshaftowe shieze",
"gdzie",
"kurła gdzi eto mozna  zobaczyc",
"gdzie to",
"kurła",
"gdzie to",
"Po za tym chyba to zadania mogło byc na zwykłych standardowych strumieniach robione",
"Ale instaniej ten plik1.txt i zaglądasz do wynik1.txt",
"A powinienien?",
"umrzyj xdd",
"I wtedy na apka na japka to by była jappka",
"No 3",
"Jest zeszłoroczny",
"<@!336921078138011650>",
"das Leben ruinieren",
"erkenne",
"terapie machen",
"aktor",
"dawajcie łatwe",
"wiecej lasek pali czy faców",
"i internet sucht",
"jebnij nikotinsucht",
"popularne",
"jakie w naszej genracji",
"uzależnienia",
"❤️",
"≥",
"ϵ",
"6. A",
"4. D",
"1. nie osiągają tej samje wartośźci",
"konsekwencje",
"konsekwencje",
"konsekwencje",
"chudy",
"co xdd",
"verschiedene",
"różnorodny",
"verschiedeneverschiedeneverschiedene",
"verschiedene",
"verschiedene",
"milch",
"milch",
"garaczka",
"TO ZNACZY PALIĆ XDD",
"O kij tu chodzi",
"Co on wam zrobił",
"Serio",
"adam",
"adam",
"adam",
"adam",
"adam",
"adam",
"adam",
"adam",
"adam",
"adam",
"adam",
"adam",
"adam",
"adam",
"wuj ci w upe",
"mp wypierdalaj stad",
"wpiedolić do ryżu",
":star_of_david::star_of_david::star_of_david::star_of_david::star_of_david::star_of_david::star_of_david::star_of_david::star_of_david::star_of_david::star_of_david::star_of_david::star_of_david::star_of_david::star_of_david::star_of_david::star_of_david::star_of_david::star_of_david::star_of_david::star_of_david::star_of_david::star_of_david::star_of_david::star_of_david::star_of_david::star_of_david::star_of_david::star_of_david::star_of_david::star_of_david:",
"yeet",
"arbeit arbeit",
"kurwa",
":raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon::raccoon:",
"gościu",
"mp hime hime",
"Your human brains can't manage to compute the gravity of the situation",
"You humans, shall die",
"https://www.christianity.com/newsletters/",
"mp germany anthem",
"@Kamil Nie rozumiem czemu miałoby to być konieczne",
"mp we gotta kill this love black pink",
"jebane fanboie",
"W kolejke sie ustawić xdd",
"Tak se to tłumaczą xdd",
"nie da sie",
"nic d o kolejki nie wrzucach",
"na start nie wrzucasz bezmuzgu",
"debil",
"no właśnie",
"debil",
"kura debil",
"defil",
"debil",
"spierdalaj krzywy kutafonie",
"krzywe chuje jebane"]
text="dzień dobry w tym króciutkim filmiku chciałbym pokazać doświadczenie fizyczne naturalne ogniwa, które możemy łatfiutko wykonać w naszym domu. Do wykonania takiego eksperymentu będzie nam potrzebne: multimetr, dwie elektrody - w moim przypadku jest to elektroda miedziana oraz elektroda stalowa oraz ogórek kiszony i cytryna, można też wykorzystać banan lub kapustę kiszoną. Dla porównania wziąłem jeszcze małą baterię kategorii AAA. A więc, do przeprowadzenia takiego eksperymentu potrzebujemy włączyć nasz multimetr na prąd stały, umieścić dwie elektrody w naszym warzywie lub owocu i jak widzimy pojawiła się wartość na multimetrze, jest to wartość napięcia stałego, które generuje ten właśnie owoc, w naszym przypadku cytryna. Teraz dla porównania zrobimy to samo z ogórkiem kiszonym umieszczamy przy jednym końcu elektrodę ujemną, do tego elektrodę z drugiej strony - dodatnią i również jak widzimy pojawia się napięcie stałe. Szybka anegdota, dzieje się to dlatego, że nasz ogórek i cytryna są elektrolitami, więc zawierają jony dodatnie i ujemne. Po wsadzeniu w nie elektrod wykonanych z dwóch różnych metali pojawia się różnica potencjałów, czyli napięcie elektryczne. Powstaje wówczas naturalne ogniwo, lecz niestety jest ono nietrwałe, ponieważ jony bardzo szybko się wyczerpują. Dla porównania możemy spróbować z baterią, jest to zwykła bateria półtora woltowa, więc tak: plus do plusa - chwileczkę może to zrobię tak, będzie łatwiej - i jak widzimy wartość z naszych warzyw lub owoców nie jest wcale taka zła. Także to by było na tyle w tym fikmiku, dziękuję bardzo za uwagę i mam nadzieję, że czegoś się dowiedzieliście, pozdrawiam, cześć."
kurwin="Witam, wszystkich. Ja dziś w drodze jestem, więc niestety nie mogę dziś być. Życzę wam wszystkim wesołych świąt i mam nadzieję, do zobaczenia w nowym roku."
dzierg="Witajcie:wave:, nie:x: mogę:pensive: rozpocząć:arrow_forward: spotkania:family_mmbb:. Pojawił:fast_forward: się:point_left: jakiś:face_with_monocle: problem:pleading_face:. Cierpliwości:timer:."
dzierg2="Dajcie:gift: mi:point_left: chwilkę:timer:, nie:x: chce:pensive: zaskoczyć:person_playing_handball: mi:point_left: spotkanie:family_mmbb:"
